# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

u1 = User.create(email: "parisi.aaron@gmail.com")
u2 = User.create(email: "aaronparisi@yahoo.com")
u3 = User.create(email: "aarons_coding_stuff@gmail.com")
u4 = User.create(email: "parisia2@hartwick.edu")
u5 = User.create(email: "aparisi@1031services.com")

ShortenedUrl.create_short_url(u1, "www.news.google.com")
ShortenedUrl.create_short_url(u2, "www.espn.com")
ShortenedUrl.create_short_url(u2, "www.pornhub.com")
ShortenedUrl.create_short_url(u5, "www.1031services.com")
ShortenedUrl.create_short_url(u5, "www.webmd.com")
ShortenedUrl.create_short_url(u5, "www.facebook.com")
ShortenedUrl.create_short_url(u3, "www.github.com")
ShortenedUrl.create_short_url(u4, "www.hartwick.edu")

TagTopic.create(name: "News")
TagTopic.create(name: "Sports")
TagTopic.create(name: "Entertainment")
TagTopic.create(name: "Finance")
TagTopic.create(name: "Health")
TagTopic.create(name: "Social Media")
TagTopic.create(name: "Tech")
TagTopic.create(name: "Other")

Tagging.create(tag_topic_id: 1, shortened_url_id: 1)
Tagging.create(tag_topic_id: 2, shortened_url_id: 2)
Tagging.create(tag_topic_id: 3, shortened_url_id: 3)
Tagging.create(tag_topic_id: 4, shortened_url_id: 4)
Tagging.create(tag_topic_id: 5, shortened_url_id: 5)
Tagging.create(tag_topic_id: 6, shortened_url_id: 6)
Tagging.create(tag_topic_id: 7, shortened_url_id: 7)
Tagging.create(tag_topic_id: 8, shortened_url_id: 8)

Visit.create(shortened_url_id: 1, user_id: 1)
Visit.create(shortened_url_id: 2, user_id: 1)
Visit.create(shortened_url_id: 3, user_id: 1)
Visit.create(shortened_url_id: 4, user_id: 1)
Visit.create(shortened_url_id: 5, user_id: 1)
Visit.create(shortened_url_id: 5, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 6, user_id: 1)
Visit.create(shortened_url_id: 8, user_id: 1)
Visit.create(shortened_url_id: 8, user_id: 1)
Visit.create(shortened_url_id: 8, user_id: 1)
Visit.create(shortened_url_id: 8, user_id: 1)